package bsoelch.concat;

public enum InternalFieldName {
    TYPE_OF,
    CONTENT,IN_TYPES,OUT_TYPES,TYPE_NAME,TYPE_FIELDS,
    IS_ENUM,IS_LIST,IS_PROC,IS_OPTIONAL,IS_TUPLE,IS_STRUCT, IS_MUTABLE, IS_MAYBE_MUTABLE,
    IS_ARRAY,IS_MEMORY,
    LENGTH,
    HAS_VALUE, IS_UNION,
}
