package bsoelch.concat;

public enum OperatorType {
    REF_ID,CLONE,DEEP_CLONE,
    NEGATE,PLUS,MINUS,
    INVERT, MULTIPLY,DIV,MOD, UNSIGNED_DIV,UNSIGNED_MOD,
    POW,
    NOT,FLIP,AND,OR,XOR,
    LOG,FLOOR,CEIL,
    LSHIFT,SLSHIFT,RSHIFT,SRSHIFT,
    GT,GE,EQ,NE,LE,LT,//value equality
    REF_EQ,REF_NE,//reference equality
    CAST,TYPE_OF,
    LIST_OF, CONTENT,
    NEW_LIST,LENGTH,ENSURE_CAP,FILL,
    GET_INDEX,SET_INDEX,GET_SLICE,SET_SLICE,
    PUSH_FIRST,PUSH_ALL_FIRST,PUSH_LAST,PUSH_ALL_LAST,
    TUPLE,NEW,
    CALL,
    INT_AS_FLOAT,FLOAT_AS_INT,
    OPEN,CLOSE,SIZE,POS,SEEK,SEEK_END,READ,WRITE,TRUNCATE
}
